// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaB-n2JMDsPreiPLAc2iH-JRhBZIJho6A',
    appId: '1:241735631705:web:7aa0a44626165cf699c248',
    messagingSenderId: '241735631705',
    projectId: 'healthcare-app-1481b',
    authDomain: 'healthcare-app-1481b.firebaseapp.com',
    storageBucket: 'healthcare-app-1481b.firebasestorage.app',
    measurementId: 'G-JRQMDC89HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOvvR-_eBIpFlPxtaoiq_soUqudpPB6lc',
    appId: '1:241735631705:android:7ff28a086d4f37dc99c248',
    messagingSenderId: '241735631705',
    projectId: 'healthcare-app-1481b',
    storageBucket: 'healthcare-app-1481b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1qATXjZXDk7s4_1hc3jlHhxYDZM3EQpc',
    appId: '1:241735631705:ios:655f401aa780b73499c248',
    messagingSenderId: '241735631705',
    projectId: 'healthcare-app-1481b',
    storageBucket: 'healthcare-app-1481b.firebasestorage.app',
    iosBundleId: 'com.example.healthcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1qATXjZXDk7s4_1hc3jlHhxYDZM3EQpc',
    appId: '1:241735631705:ios:655f401aa780b73499c248',
    messagingSenderId: '241735631705',
    projectId: 'healthcare-app-1481b',
    storageBucket: 'healthcare-app-1481b.firebasestorage.app',
    iosBundleId: 'com.example.healthcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaB-n2JMDsPreiPLAc2iH-JRhBZIJho6A',
    appId: '1:241735631705:web:cf21308619f9739b99c248',
    messagingSenderId: '241735631705',
    projectId: 'healthcare-app-1481b',
    authDomain: 'healthcare-app-1481b.firebaseapp.com',
    storageBucket: 'healthcare-app-1481b.firebasestorage.app',
    measurementId: 'G-GS8X98VD8Z',
  );
}
