// Generated by Flutter Assets

// ignore_for_file: unused_field, camel_case_types, non_constant_identifier_names, library_private_types_in_public_api

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

class Assets extends StatelessWidget {
  final AssetsData assets;
  final Widget child;

  const Assets({
    super.key,
    required this.assets,
    required this.child,
  });

  static AssetsData of(BuildContext context) {
    final widget =
        context.dependOnInheritedWidgetOfExactType<_InheritedAssets>();
    return widget?.assets ?? AssetsData.light();
  }

  @override
  Widget build(BuildContext context) {
    return _InheritedAssets(
      assets: assets,
      child: child,
    );
  }
}

class _InheritedAssets extends InheritedWidget {
  final AssetsData assets;

  const _InheritedAssets({
    required this.assets,
    required super.child,
  });

  @override
  bool updateShouldNotify(covariant _InheritedAssets oldWidget) =>
      assets != oldWidget.assets;
}

class AssetsData {
  static AssetsData? _light;
  static AssetsData? _dark;

  factory AssetsData.light() =>
      _light ??= AssetsData._(brightness: Brightness.light);
  factory AssetsData.dark() =>
      _dark ??= AssetsData._(brightness: Brightness.dark);
  factory AssetsData.brightness(Brightness brightness) =>
      brightness == Brightness.light ? AssetsData.light() : AssetsData.dark();

  final Brightness _brightness;

  AssetsData._({
    required Brightness brightness,
  })  : _brightness = brightness,
        fonts = _assets_fonts_dart._(brightness: brightness),
        icons = _assets_icons_dart._(brightness: brightness),
        images = _assets_images_dart._(brightness: brightness);

  final _assets_fonts_dart fonts;
  final _assets_icons_dart icons;
  final _assets_images_dart images;
}

class _assets_fonts_dart {
  final Brightness _brightness;

  _assets_fonts_dart._({
    required Brightness brightness,
  }) : _brightness = brightness;

  final Poppins_Bold_ttf = 'assets/fonts/Poppins-Bold.ttf';
  final Poppins_Light_ttf = 'assets/fonts/Poppins-Light.ttf';
  final Poppins_Medium_ttf = 'assets/fonts/Poppins-Medium.ttf';
  final Poppins_Regular_ttf = 'assets/fonts/Poppins-Regular.ttf';
  final Poppins_Thin_ttf = 'assets/fonts/Poppins-Thin.ttf';
}

class _assets_icons_dart {
  final Brightness _brightness;

  _assets_icons_dart._({
    required Brightness brightness,
  }) : _brightness = brightness;

  final logo_svg = 'assets/icons/logo.svg';
}

class _assets_images_dart {
  final Brightness _brightness;

  _assets_images_dart._({
    required Brightness brightness,
  }) : _brightness = brightness;

  final back_icon_svg = 'assets/images/back_icon.svg';
  final body_icon_svg = 'assets/images/body_icon.svg';
  final doctor_one_png = 'assets/images/doctor_one.png';
  final doctor_three_png = 'assets/images/doctor_three.png';
  final doctor_two_png = 'assets/images/doctor_two.png';
  final email_icon_svg = 'assets/images/email_icon.svg';
  final eye_icon_svg = 'assets/images/eye_icon.svg';
  final facebook_icon_svg = 'assets/images/facebook_icon.svg';
  final favorite_icon_svg = 'assets/images/favorite_icon.svg';
  final google_icon_svg = 'assets/images/google_icon.svg';
  final heart_icon_svg = 'assets/images/heart_icon.svg';
  final home_icon_svg = 'assets/images/home_icon.svg';
  final onboarding1_png = 'assets/images/onboarding1.png';
  final onboarding2_png = 'assets/images/onboarding2.png';
  final password_icon_svg = 'assets/images/password_icon.svg';
  final profile_icon_svg = 'assets/images/profile_icon.svg';
  final profile_image_png = 'assets/images/profile_image.png';
  final report_icon_svg = 'assets/images/report_icon.svg';
  final tooth_icon_svg = 'assets/images/tooth_icon.svg';
  final user_icon_svg = 'assets/images/user_icon.svg';

  static const String mySelf = 'assets/images/mySelf.png';
  static const String child = 'assets/images/child.png';
  static const String wife = 'assets/images/wife.png';
  static const String parents = 'assets/images/parents 2.png';
}
